### ISSUE TITLE
[doc] could you document how this was made faster than other solutions ?

### ISSUE THREAD

**Issue by thomasleveil** [sonic182/aiosonic#315]
Hi,

Could you add a section in the readme file describing the technics or technological choices you made in order to make it fast ?

**Comment by sonic182** [comment]
Mmmm it is a mystery for me about how it is fast, maybe because using cache in some points, very simplistic code to do exactly what is needed, etc...

At the end, most of the work is made by the python C code (socket, ssl, regex module)

If I get an idea about how to make the doc you propose, I do it
